collection/urls.py
from django.urls import path
import collection.views as cv

urlpatterns = [
    path('', cv.index.as_view(), name='collection_index'),
    path('mtg/', cv.mtg_index.as_view(), name='mtg_index'),
    path('mtg/sets', cv.mtg_set_list.as_view(), name='mtg_set_list'),
    path('mtg/view_set/<str:set_short>', cv.mtg_view_set.as_view(), name='mtg_view_set'),
    path('mtg/my_collection', cv.mtg_my_sets.as_view(), name='mtg_my_sets'),
    path('mtg/search', cv.mtg_search_cards.as_view(), name='mtg_search'),
    path('mtg/results', cv.mtg_search_results.as_view(), name='mtg_results'),
    path('mtg/custom/create', cv.mtg_create_custom_set.as_view(), name='mtg_custom_create'),
    path('mtg/custom/sets', cv.mtg_list_custom_sets.as_view(), name='mtg_custom_list'),
    path('mtg/custom/edit_collection/<int:id>', cv.mtg_edit_custom_set.as_view(), name='mtg_custom_edit'),
    path('mtg/search_json', cv.mtg_search_cards_json.as_view(), name='mtg_search_json'),
]

home/urls.py
from django.urls import path, include
import home.views as hv

urlpatterns = [
    path('', hv.Index.as_view(), name='home_index'),
]

tcgct_main/urls.py
from django.contrib import admin
from django.urls import path, include
from tcgct_admin import views as tcgav

urlpatterns = [
    path('login', tcgav.login_view.as_view(), name='login_view'),
    path('logout', tcgav.logout_view, name='logout_view'),
    path('register', tcgav.register_view.as_view(), name='register_view'),
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('collection/', include('collection.urls')),
]

collection/models/mtg.py
from django.contrib.auth.models import User
from django.db import models
import requests


class MTG_Rarity(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.name}'


class MTG_SetType(models.Model):
    name = models.CharField(max_length=50)


class MTG_Set(models.Model):
    name = models.CharField(max_length=100)
    shorthand = models.CharField(max_length=20)
    icon = models.URLField(max_length=300, null=True)
    search_uri = models.URLField(max_length=500)
    set_type = models.ForeignKey(MTG_SetType, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.shorthand} - {self.name}'


class MTG_CardType(models.Model):
    name = models.CharField(max_length=300)

    def __str__(self):
        return f'{self.name}'


# W = White
# U = Blue
# B = Black
# R = Red
# G = Green
class MTG_Card(models.Model):
    name = models.CharField(max_length=200)
    card_set = models.ForeignKey(MTG_Set, on_delete=models.CASCADE, blank=False, null=False)
    mana_cost = models.CharField(max_length=50, null=True)
    converted_cost = models.IntegerField(null=True)  
    text = models.CharField(max_length=1000, null=True)
    flavor = models.CharField(max_length=1000, null=True)
    artist = models.CharField(max_length=100, null=True)
    collector_number = models.CharField(max_length=25, null=False)
    power = models.CharField(max_length=10, null=True)
    toughness = models.CharField(max_length=10, null=True)
    scryfall_id = models.CharField(max_length=36)
    oracle_id = models.CharField(max_length=36)

    rarity = models.ForeignKey(MTG_Rarity, on_delete=models.CASCADE)
    # image will be face, flipped will be back
    image = models.URLField(null=True)
    image_flipped = models.URLField(null=True)

    def __str__(self):
        return f'{self.name} - {self.card_set.shorthand} - {self.collector_number}'


class MTG_TypeLine(models.Model):
    type = models.ForeignKey(MTG_CardType, on_delete=models.CASCADE, blank=False, null=False)
    card = models.ForeignKey(MTG_Card, on_delete=models.CASCADE, blank=False, null=False)

    def __str__(self):
        return f'{self.card.name} - {self.type.name}'


class MTG_Collected(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    card = models.ForeignKey(MTG_Card, on_delete=models.CASCADE)
    normal = models.IntegerField()
    foil = models.IntegerField()

    def __str__(self):
        return f'{self.owner} | {self.card.name} | {self.card.card_set.shorthand} | {self.normal} | {self.foil}'


class MTG_Custom_Set(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, null=False)
    description = models.TextField(max_length=2000, null=False)


class MTG_Custom_Set_Cards(models.Model):
    custom_set = models.ForeignKey(MTG_Custom_Set, on_delete=models.CASCADE)
    card = models.ForeignKey(MTG_Card, on_delete=models.CASCADE)
    normal = models.IntegerField()
    foil = models.IntegerField()

collection/forms.py
from email.policy import default
from pickle import FALSE
from django import forms
from pkg_resources import require
from collection.models.mtg import MTG_Set, MTG_CardType

class MTGSearchForm(forms.Form):
    name = forms.CharField(max_length=200, required=False)
    converted_cost = forms.CharField(max_length=6, required=False)
    types_select = forms.ModelChoiceField(queryset=MTG_CardType.objects.all(), required=False)
    types = forms.CharField(max_length=500, required=False)
    power = forms.CharField(max_length=3, required=False)
    toughness = forms.CharField(max_length=3, required=False)
    search_collection = forms.BooleanField(initial=False, required=False)


class MTGCreateCustomSetForm(forms.Form):
    title = forms.CharField(min_length=1, max_length=200)
    description = forms.CharField(max_length=2000)

collection/views.py
import json
from django.shortcuts import render, redirect
from django.views import View
from collection.models import mtg
from collection.forms import MTGSearchForm, MTGCreateCustomSetForm
from difflib import SequenceMatcher
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse

def similar(a, b):
    if a.lower() in b.lower() or b.lower() in a.lower():
        return 1
    return SequenceMatcher(None, a.lower(), b.lower()).ratio()


class index(View):
    def get(self, request):
        return render(
            request,
            'index.html',
            {

            }
        )


class mtg_index(View):
    def get(self, request):
        return render(
            request,
            'mtg/index.html',
            {
                
            }
        )


class mtg_set_list(View):
    def get(self, request):
        _data = list(mtg.MTG_Set.objects.all().values())
        data = [{'name':x['name'], 'shorthand':x['shorthand'], 'set_type':mtg.MTG_SetType.objects.filter(id=x['set_type_id']).first().name, 'icon':x['icon']} for x in _data]
        for d in data:
            if d['icon'] is None:
                d['icon'] = ''
        return render(
            request,
            'mtg/sets.html',
            {
                'data': data
            }
        )


class mtg_view_set(LoginRequiredMixin, View):
    def get(self, request, set_short):
        _temp = mtg.MTG_Set.objects.filter(shorthand=set_short).first()
        set_name = _temp.name
        shorthand = _temp.shorthand

        _data = list(mtg.MTG_Card.objects.filter(card_set__shorthand=set_short).values())
        data = []
        for d in _data:
            for u in d:
                if u == 'rarity_id':
                    d[u] = mtg.MTG_Rarity.objects.filter(id=d[u]).first().name.capitalize()
                if d[u] == None:
                    # None cannot be used in tabulator
                    d[u] = ''
            _temp = d

            # Add readable type line to dict
            type_line_str = ''
            type_line = mtg.MTG_TypeLine.objects.filter(card__id=d['id'])
            for tl in type_line:
                type_line_str = type_line_str + tl.type.name.lower().capitalize() + ' '
            _temp['type_line'] = type_line_str.strip()

            _temp['image_url'] = d['image']

            # Add collected count to dict
            collected = mtg.MTG_Collected.objects.filter(owner=request.user, card__id=d['id'])
            if collected.exists():
                collected = collected.first()
                _temp['normal'] = collected.normal
                _temp['foil'] = collected.foil
            else:
                _temp['normal'] = 0
                _temp['foil'] = 0

            data.append(_temp)                
        return render(
            request,
            'mtg/view_set.html',
            {
                'card_set':set_name,
                'data': data,
                'shorthand': shorthand
            }
        )

    def post(self, request, set_short):
        data = json.loads(request.POST.get('Data'))
        for d in data:
            card = mtg.MTG_Card.objects.filter(
                        id=d['id'],
                        card_set__id=d['card_set_id'],
                        collector_number=d['collector_number']
                    ).first()

            collection_item = mtg.MTG_Collected.objects.filter(
                owner = request.user,
                card = card
            )

            if not collection_item.exists() and (d['foil'] > 0 or d['normal'] > 0):
                collection_item = mtg.MTG_Collected()
                collection_item.owner = request.user
                collection_item.card = card
                collection_item.normal = d['normal']
                collection_item.foil = d['foil']
                collection_item.save()
            elif d['foil'] > 0 or d['normal'] > 0:
                collection_item = collection_item.first()
                collection_item.normal = d['normal']
                collection_item.foil = d['foil']
                collection_item.save()
            elif collection_item.exists() and (d['foil'] == 0 or d['normal'] == 0):
                collection_item.delete()

        return redirect('mtg_view_set', set_short=set_short)


class mtg_my_sets(LoginRequiredMixin, View):
    def get(self, request):
        shorts = mtg.MTG_Collected.objects.filter(owner=request.user)
        # Get all unique set codes from above
        shorts = list(set([s.card.card_set.shorthand for s in shorts]))

        _data = list(mtg.MTG_Set.objects.filter(shorthand__in=shorts).values())
        data = [{'name':x['name'], 'shorthand':x['shorthand'], 'set_type':mtg.MTG_SetType.objects.filter(id=x['set_type_id']).first().name, 'icon':x['icon']} for x in _data]

        for d in data:
            card_count = mtg.MTG_Card.objects.filter(card_set__shorthand=d['shorthand']).__len__()
            d['card_count'] = card_count
            collected_cards = mtg.MTG_Collected.objects.filter(owner=request.user, card__card_set__shorthand=d['shorthand'])
            d['single_card_collected_normal'] = len(collected_cards.filter(normal__gte=1))
            d['set_collected_normal'] = len(collected_cards.filter(normal__gte=4))

            if d['icon'] is None:
                d['icon'] = ''
            

        return render(
            request,
            'mtg/collection_sets.html',
            {
                'data': data
            }
        )


class mtg_search_cards(LoginRequiredMixin, View):
    def get(self, request):
        form = MTGSearchForm()
        return render(
            request,
            'mtg/search_cards.html',
            {
                'form':form
            }
        )


class mtg_search_results(LoginRequiredMixin, View):
    def get(self, request):
        cards = []
        query = Q()
        name_ = request.GET['name']
        converted_cost_ = request.GET['converted_cost']
        types_ = request.GET['types']
        power_ = request.GET['power']
        toughness_ = request.GET['toughness']

        if name_:
            query &= Q(name__contains=name_)
        if converted_cost_:
            query &= Q(converted_cost=converted_cost_)
        if power_:
            query &= Q(power=power_)
        if toughness_:
            query &= Q(toughness=toughness_)

        if 'search_collection' in request.GET:
            collected_ = mtg.MTG_Collected.objects.filter(owner=request.user)
            cards = [c.card for c in collected_]

        # TODO: filter first if has creature,enhancement,instant,sorcery,planeswalker
        if query != Q():
            print(query)
            cards = cards + list(mtg.MTG_Card.objects.filter(query))

        if types_:
            types = request.GET['types'].split(',')
            if '—' in types:
                types.remove('—')
            if '//' in types:
                types.remove('//')
            if '' in types:
                types.remove('')

            types_set = set(types)     
           
            if cards == []:
                type_ = mtg.MTG_CardType.objects.filter(name=types[-1])
                # list of those that have atleast one of asked for type
                typeline = mtg.MTG_TypeLine.objects.filter(type=type_.first())

                for tl in typeline:
                    ctypes = mtg.MTG_TypeLine.objects.exclude(type__id__in=[2,50]).filter(card=tl.card)
                    if len(ctypes) < len(types):
                        continue
                    type_line_list = [x.type.name for x in ctypes]
                    if types_set.issubset(set(type_line_list)):
                        cards.append(tl.card)
            else:
                cards_ = list(cards)
                cards = []
                for c in cards_:
                    ctypes = mtg.MTG_TypeLine.objects.exclude(type__id__in=[2,50]).filter(card=c)
                    if len(ctypes) < len(types):
                        continue
                    type_line_list = [x.type.name for x in ctypes]
                    if types_set.issubset(set(type_line_list)):
                        cards.append(c)


        data = []
        # TODO: should return the set of eachcard instead of collector number, thats useless when cards from multiple sets are mixed together        
        for c in cards:
            card_dict = {}
            card_dict['collector_number'] = c.collector_number 
            card_dict['name'] = c.name
            card_dict['text'] =  c.text or ''
            card_dict['flavor'] = c.flavor or ''
            card_dict['rarity_id'] = c.rarity.name.capitalize()
            card_dict['image'] = c.image

            type_line_str = ''
            type_line = mtg.MTG_TypeLine.objects.filter(card=c)
            for tl in type_line:
                type_line_str = type_line_str + tl.type.name.lower().capitalize() + ' '
            card_dict['type_line'] = type_line_str.strip()

            collected = mtg.MTG_Collected.objects.filter(owner=request.user, card=c)
            if collected.exists():
                card_dict['normal'] = collected.first().normal
                card_dict['foil'] = collected.first().foil
            else:
                card_dict['normal'] = 0
                card_dict['foil'] = 0
            data.append(card_dict)

        return render(
            request,
            'mtg/view_set.html',
            {
                'card_set':'Custom Search',
                'data': data,
                'shorthand': 'n/a'
            }
        )


class mtg_search_cards_json(View):
    def get(self, request):
        cards = []
        query = Q()

        if 'name' in request.GET:
            query &= Q(name__contains=request.GET['name'])
        if 'converted_cost' in request.GET:
            query &= Q(converted_cost=request.GET['converted_cost'])
        if 'power' in request.GET:

collection/templates/mtg/collection_sets.html
{% extends "base.html" %}

{% block extrajs%}
<link href="https://unpkg.com/tabulator-tables@5.3.4/dist/css/tabulator.min.css" rel="stylesheet">
<script type="text/javascript" src="https://unpkg.com/tabulator-tables@5.3.4/dist/js/tabulator.min.js"></script>
{% endblock %}

{% block content%}
<div>
    <select id="filter-field">
        <option></option>
        <option value="name">Name</option>
        <option value="shorthand">Shorthand</option>
        <option value="set_type">Type</option>
    </select>

    <select id="filter-type">
        <option value="=">=</option>
        <option value="<"><</option>
        <option value="<="><=</option>
        <option value=">">></option>
        <option value=">=">>=</option>
        <option value="!=">!=</option>
        <option value="like">like</option>
    </select>

    <input id="filter-value" type="text" placeholder="value to filter">

    <button id="filter-clear">Clear Filter</button>
</div>

<div id="example-table"></div>
{% endblock %}

<script>
{% block inlinejs %}
    //Define variables for input elements
    var fieldEl = document.getElementById("filter-field");
    var typeEl = document.getElementById("filter-type");
    var valueEl = document.getElementById("filter-value");

    //Custom filter example
    function customFilter(data){
        return data.car && data.rating < 3;
    }

    //Trigger setFilter function with correct parameters
    function updateFilter(){
        var filterVal = fieldEl.options[fieldEl.selectedIndex].value;
        var typeVal = typeEl.options[typeEl.selectedIndex].value;

        var filter = filterVal == "function" ? customFilter : filterVal;

        if(filterVal == "function" ){
            typeEl.disabled = true;
            valueEl.disabled = true;
        }else{
            typeEl.disabled = false;
            valueEl.disabled = false;
        }

        if(filterVal){
            table.setFilter(filter,typeVal, valueEl.value);
        }
    }

    function clearFilter(){
        fieldEl.value = "";
        typeEl.value = "=";
        valueEl.value = "";

        table.clearFilter();
    }


    //Update filters on value change
    document.getElementById("filter-field").addEventListener("change", updateFilter);
    document.getElementById("filter-type").addEventListener("change", updateFilter);
    document.getElementById("filter-value").addEventListener("keyup", updateFilter);
    document.getElementById("filter-value").addEventListener("beforeinput", testFunc);
    function testFunc(e){
        console.log(e);
        console.log(e.data);
        if(document.getElementsByClassName('tabulator-selectable').length == 1){
            if (e.data == "."){
                clearFilter();
                e.preventDefault();
                return;
            } 
            let result = document.getElementsByClassName('tabulator-selectable')[0];
            console.log(result);
            if(e.data == "+"){
                console.log("Add normal");
                e.preventDefault();
            } else if (e.data == "-") {
                console.log("Remove normal");
                e.preventDefault();
            } else if (e.data == "/"){
                console.log("Remove foil");
                e.preventDefault();
            } else if (e.data == "*"){
                console.log("Add foil");
                e.preventDefault();
            }            
        }

    }
    //Clear filters on "Clear Filters" button click
    document.getElementById("filter-clear").addEventListener("click", clearFilter);

    //Build Tabulator
    var table = new Tabulator("#example-table", {
        pagination:"local",
        paginationSize:20,
        height:"90%",
        layout:"fitColumns",
        columns:[
            {title:"Name", field:"name", width:200, formatter:"link", formatterParams:{
                urlField:"shorthand",
                urlPrefix:"view_set/",
                target:"_blank",
            }},
            {title:"Shorthand", field:"shorthand"},
            {title:"Type", field:"set_type"},
            {title:"Icon", field:"icon", formatter:"image", formatterParams:{
                height:"30px"
            }},
            {title:"Card Count", field:"card_count"},
            {title:"Singles Collected", field:"single_card_collected_normal"},
            {title:"Card Sets Collected", field:"set_collected_normal"}
        ],      
        data:{{data|safe}},
    });
{% endblock %}    
</script>

collection/templates/mtg/create_set.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block extrajs %}
<script
    src="https://code.jquery.com/jquery-3.6.1.min.js"
    integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ="
    crossorigin="anonymous"></script>
{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <hr>
    <button type="submit">Create</button>
</form>
{% endblock %}

collection/templates/mtg/custom_sets.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Update Collection</th>
            <th>Edit Base Collection</th>
        </tr>
    </thead>

    <tbody>
        {% for d in data %}
        <tr>
            <td>{{d.title}}</td>
            <td>{{d.description}}</td>
            <td>Update</td>
            <td><a href="{% url 'mtg_custom_edit' d.id %}">Edit</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

collection/templates/mtg/edit_set.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="one">
    <div class="one-one">
        <button>Save Changes</button>
    </div>
    <div class="one-two">
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Set</th>
                    <th>Image</th>
                    <th>Remove</th>
                </tr>                
            </thead>
            <tbody id="collection-cards">

            </tbody>
        </table>
    </div>
</div>
<div class="two">
    <div class="two-one">

    </div>
    <div class="two-two">

    </div>
</div>
<style>
    table{
        width:100%;
    }
    .one{
        width:50%;
        height: 100%;
        background-color: red;
        float:left;
    }
    .two{
        width:50%;
        height: 100%;
        background-color: blue;
        float:right;
    }

    .one-one{
        width:100%;
        height:10%;
        background-color: green;
    }

    .one-two{
        width:100%;
        height:90%;
        background-color: aqua;
    }

    .two-one{
        width:100%;
        height:20%;
        background-color: yellow;
    }

    .two-two{
        width:100%;
        height:80%;
        background-color: blueviolet;
    }
</style>
{% endblock %}

collection/templates/mtg/index.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/collection_list.css' %}">
{% endblock %}

{% block content %}

<div class="list-group">
    <a href="{% url 'mtg_set_list' %}" class="list-group-item list-group-item-action">View All Sets</a>
    <a href="{% url 'mtg_my_sets' %}" class="list-group-item list-group-item-action">View My Sets</a>
    <a href="{% url 'mtg_search' %}" class="list-group-item list-group-item-action">Search Cards</a>
    <a href="{% url 'mtg_custom_create' %}" class="list-group-item list-group-item-action">Create New Set</a>
    <a href="{% url 'mtg_custom_list' %}" class="list-group-item list-group-item-action">View Custom Sets</a>
</div>

{% endblock %}

collection/templates/mtg/search_cards.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block extrajs %}
<script
    src="https://code.jquery.com/jquery-3.6.1.min.js"
    integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ="
    crossorigin="anonymous"></script>
{% endblock %}

{% block content %}
{% csrf_token %}
<form method="get" action="{% url 'mtg_results' %}" enctype="multipart/form-data">
    {{form|crispy}}
    <hr>
    <button type="submit">Search</button>
</form>
<p>Note: You cannot add cards to your collection from this search</p>
{% endblock %}

<script>
    {% block inlinejs %}
    $('#id_types_select').change(function(){
        let prev = $('#id_types').val() + "," + $('#id_types_select option:selected').text();
        $('#id_types').val(prev);
    });
    {% endblock %}
</script>

collection/templates/mtg/sets.html
{% extends "base.html" %}

{% block extrajs%}
<link href="https://unpkg.com/tabulator-tables@5.3.4/dist/css/tabulator.min.css" rel="stylesheet">
<script type="text/javascript" src="https://unpkg.com/tabulator-tables@5.3.4/dist/js/tabulator.min.js"></script>
{% endblock %}

{% block content%}
<div>
    <select id="filter-field">
        <option></option>
        <option value="name">Name</option>
        <option value="shorthand">Shorthand</option>
        <option value="set_type">Type</option>
    </select>

    <select id="filter-type">
        <option value="=">=</option>
        <option value="<"><</option>
        <option value="<="><=</option>
        <option value=">">></option>
        <option value=">=">>=</option>
        <option value="!=">!=</option>
        <option value="like">like</option>
    </select>

    <input id="filter-value" type="text" placeholder="value to filter">

    <button id="filter-clear">Clear Filter</button>
</div>

<div id="example-table"></div>
{% endblock %}

<script>
{% block inlinejs %}
    //Define variables for input elements
    var fieldEl = document.getElementById("filter-field");
    var typeEl = document.getElementById("filter-type");
    var valueEl = document.getElementById("filter-value");

    //Custom filter example
    function customFilter(data){
        return data.car && data.rating < 3;
    }

    //Trigger setFilter function with correct parameters
    function updateFilter(){
        var filterVal = fieldEl.options[fieldEl.selectedIndex].value;
        var typeVal = typeEl.options[typeEl.selectedIndex].value;

        var filter = filterVal == "function" ? customFilter : filterVal;

        if(filterVal == "function" ){
            typeEl.disabled = true;
            valueEl.disabled = true;
        }else{
            typeEl.disabled = false;
            valueEl.disabled = false;
        }

        if(filterVal){
            table.setFilter(filter,typeVal, valueEl.value);
        }
    }

    function clearFilter(){
        fieldEl.value = "";
        typeEl.value = "=";
        valueEl.value = "";

        table.clearFilter();
    }


    //Update filters on value change
    document.getElementById("filter-field").addEventListener("change", updateFilter);
    document.getElementById("filter-type").addEventListener("change", updateFilter);
    document.getElementById("filter-value").addEventListener("keyup", updateFilter);
    document.getElementById("filter-value").addEventListener("beforeinput", testFunc);
    function testFunc(e){
        console.log(e);
        console.log(e.data);
        if(document.getElementsByClassName('tabulator-selectable').length == 1){
            if (e.data == "."){
                clearFilter();
                e.preventDefault();
                return;
            } 
            let result = document.getElementsByClassName('tabulator-selectable')[0];
            console.log(result);
            if(e.data == "+"){
                console.log("Add normal");
                e.preventDefault();
            } else if (e.data == "-") {
                console.log("Remove normal");
                e.preventDefault();
            } else if (e.data == "/"){
                console.log("Remove foil");
                e.preventDefault();
            } else if (e.data == "*"){
                console.log("Add foil");
                e.preventDefault();
            }            
        }

    }
    //Clear filters on "Clear Filters" button click
    document.getElementById("filter-clear").addEventListener("click", clearFilter);

    //Build Tabulator
    var table = new Tabulator("#example-table", {
        pagination:"local",
        paginationSize:20,
        height:"90%",
        layout:"fitColumns",
        columns:[
            {title:"Name", field:"name", width:200, formatter:"link", formatterParams:{
                urlField:"shorthand",
                urlPrefix:"view_set/",
                target:"_blank",
            }},
            {title:"Shorthand", field:"shorthand"},
            {title:"Type", field:"set_type"},
            {title:"Icon", field:"icon", formatter:"image", formatterParams:{
                height:"30px"
            }}
        ],
        data:{{data|safe}},
    });
{% endblock %}    
</script>